---
apiVersion: v1
kind: ConfigMap

metadata:
  name: employee-app-config
  namespace: {{ .Values.namespace }}

data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-svc:5432/employees

  POSTGRES_DB: {{ .Values.postgres.database }}
---
