---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
  namespace: vk67220-ns
spec:
  #replicas: 3     # For HPA we will set replicas to 1 and let HPA manage the scaling
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          #image: prasad5806/springboot-postgresql-hibernate-crud-example-app:latest
          image: 302524629943.dkr.ecr.us-east-1.amazonaws.com/employees-app-dev:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: employee-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: employee-app-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-app-secrets
                  key: SPRING_DATASOURCE_PASSWORD
---