---
apiVersion: v1
kind: Service
metadata:
  name: employee-app-svc
  namespace: vk67220-ns
spec:
  #type: LoadBalancer   # For EKS Cluster with AWS Load Balancer Controller
  type: ClusterIP       # when using ingress controller type should be ClusterIP
  selector:
    app: employee-app
  ports:
    - name: http  
      port: 80
      targetPort: 8080
---