name: Maven Build & Package
description: Setup Java 17 and build Maven project

inputs:
  java-version:
    description: "Java version to use for the build"
    required: false
    default: "17"

outputs:
  build-status:
    description: "Build result"
    value: ${{ steps.build.outputs.status }}

  java-version:
    description: "Java version used"
    value: ${{ steps.java.outputs.version }}

runs:
  using: composite
  steps:
    
    - name: Validate Java version
      if: ${{ inputs.java-version != '17' }}
      run: |
        echo "Only Java 17 is supported"
        exit 1
      shell: bash

    
    - name: Setup Java
      id: java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    
    - name: Capture Java version
      id: java-version
      run: |
        VERSION=$(java -version 2>&1 | head -n 1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash

    
    - name: Build with Maven
      id: build
      run: |
        mvn clean package -DskipTests
        echo "status=success" >> $GITHUB_OUTPUT
      shell: bash
