name: Maven Build & Package
description: Setup Java, verify Maven, and build package

inputs:
  java-version:
    description: 'Java version to use (e.g., 17)'
    required: false
    default: "17"

outputs:
  build-status:
    description: 'Status of the Maven build'
    value: ${{ job.status }}
  java-version-check:
    description: 'Result of Java version check'
    value: ${{ steps.setup-java.outputs.java-version }}

runs:
  using: composite
  steps:
    - name: Validate JDK
      if: ${{ inputs.java-version == '17' }}
      run: |
        echo "Only Java 17 is supported. You provided: ${{ inputs.java-version }}"
      shell: bash

    - name: Set up JDK
      id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
        cache: maven

    - name: Verify Maven
      run: mvn -version
      shell: bash

    - name: Build with Maven
      run: |
        mvn clean package -DskipTests
        ls -la target/
      shell: bash

    - name: Down Docker Compose
      run: docker compose down
      shell: bash
