name: Maven Build & Package
description: Setup Java, verify Maven, and build package

inputs:
  java-version:
    description: 'Java version to use (e.g., 17)'
    required: false
    default: "17"

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      if: ${{ inputs.java-version == '17' }}
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
        cache: maven

    - name: Verify Maven
      run: mvn -version
      shell: bash

    - name: Build with Maven
      run: |
        mvn clean package -DskipTests
        ls -la target/
      shell: bash

    - name: Down Docker Compose
      run: docker compose down
      shell: bash
