name: Install EBS CSI Driver

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - production

jobs:
  install-ebs-csi:
    runs-on: self-hosted

    environment: ${{ inputs.target_env }}

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:

      #########################################
      # STEP 1 - Checkout Repository
      #########################################
      - name: Checkout Code
        uses: actions/checkout@v4

      #########################################
      # STEP 2 - Configure AWS Credentials
      #########################################
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #########################################
      # STEP 3 - Verify AWS Identity
      #########################################
      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      #########################################
      # STEP 4 - Configure kubeconfig
      #########################################
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${AWS_REGION} \
            --name ${CLUSTER_NAME}

      #########################################
      # STEP 5 - Verify EKS Cluster
      #########################################
      - name: Verify EKS Cluster
        run: |
          kubectl get nodes

          aws eks describe-cluster \
            --name ${CLUSTER_NAME} \
            --region ${AWS_REGION}

      #########################################
      # STEP 6 - Install eksctl
      #########################################
      - name: Install eksctl
        run: |
          curl --silent --location \
          "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
          | tar xz -C /tmp

          sudo mv /tmp/eksctl /usr/local/bin

          eksctl version

      #########################################
      # STEP 7 - Associate IAM OIDC Provider
      #########################################
      - name: Associate IAM OIDC Provider
        run: |
          eksctl utils associate-iam-oidc-provider \
            --cluster ${CLUSTER_NAME} \
            --region ${AWS_REGION} \
            --approve

      #########################################
      # STEP 8 - Get OIDC ID
      #########################################
      - name: Get OIDC ID
        id: oidc
        run: |

          OIDC_URL=$(aws eks describe-cluster \
            --name ${CLUSTER_NAME} \
            --query "cluster.identity.oidc.issuer" \
            --output text)

          echo "OIDC_URL=$OIDC_URL"

          OIDC_ID=$(echo $OIDC_URL | awk -F '/' '{print $NF}')

          echo "OIDC_ID=$OIDC_ID" >> $GITHUB_ENV

      #########################################
      # STEP 9 - Create Trust Policy
      #########################################
      - name: Create Trust Policy
        run: |

          cat <<EOF > ebs-trust-policy.json
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/oidc.eks.${AWS_REGION}.amazonaws.com/id/${OIDC_ID}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "oidc.eks.${AWS_REGION}.amazonaws.com/id/${OIDC_ID}:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                  }
                }
              }
            ]
          }
          EOF

          cat ebs-trust-policy.json

      #########################################
      # STEP 10 - Create IAM Role
      #########################################
      - name: Create IAM Role
        run: |

          aws iam create-role \
            --role-name AmazonEKS_EBS_CSI_DriverRole \
            --assume-role-policy-document file://ebs-trust-policy.json \
          || echo "IAM Role already exists"

      #########################################
      # STEP 11 - Attach EBS CSI Policy
      #########################################
      - name: Attach EBS CSI Policy
        run: |

          aws iam attach-role-policy \
            --role-name AmazonEKS_EBS_CSI_DriverRole \
            --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
          || echo "Policy already attached"

      #########################################
      # STEP 12 - Install EBS CSI Driver Add-on
      #########################################
      - name: Install EBS CSI Driver
        run: |

          aws eks create-addon \
            --cluster-name ${CLUSTER_NAME} \
            --addon-name aws-ebs-csi-driver \
            --service-account-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKS_EBS_CSI_DriverRole \
            --region ${AWS_REGION} \
          || echo "Addon already exists"

      #########################################
      # STEP 13 - Wait for Add-on
      #########################################
      - name: Wait for Add-on
        run: |

          aws eks wait addon-active \
            --cluster-name ${CLUSTER_NAME} \
            --addon-name aws-ebs-csi-driver \
            --region ${AWS_REGION}

      #########################################
      # STEP 14 - Verify EBS CSI Pods
      #########################################
      - name: Verify EBS CSI Pods
        run: |

          kubectl get pods -n kube-system | grep ebs

      #########################################
      # STEP 15 - Verify Storage Classes
      #########################################
      - name: Verify StorageClass
        run: |

          kubectl get storageclass

      #########################################
      # STEP 16 - Verify CSI Driver Addon
      #########################################
      - name: Verify EBS CSI Addon
        run: |

          aws eks describe-addon \
            --cluster-name ${CLUSTER_NAME} \
            --addon-name aws-ebs-csi-driver \
            --region ${AWS_REGION}