name: crud pagination sorting webapp CI with Nexus

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted

    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Maven
        run: mvn -version

      - name: Compile
        run: mvn compile

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${NEXUS_USERNAME}</username>
                <password>${NEXUS_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to Nexus
        run: mvn deploy